on: [pull_request, push]
jobs:
  # GitHub Actions provides only Python 3.5 and newer for macOS and Ubuntu 20.04.
  # There is Python 3.4 for Ubuntu 18.04,
  # but GitHub doesn't provide any runners for Ubuntu 18.04 anymore.
  # Can't update to Ubuntu 22.04,
  # because only Python 3.7 and newer are provided there.
  # Windows is the only platform where the entire range of Python versions is available.
  test:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-20.04]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.5"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.6"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade tox
      - run: tox
        env:
          TOX_SKIP_ENV: py34
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.4"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.5"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.6"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade tox
      - run: tox
